<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2xvexfx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2xvexfx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2xvexfx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2xvexfx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container2xvexfx\srcDevDebugProjectContainer(array(
    'container.build_hash' => '2xvexfx',
    'container.build_id' => 'e583007b',
    'container.build_time' => 1542014578,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2xvexfx');
