<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPlw2MxN\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPlw2MxN/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPlw2MxN.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPlw2MxN\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPlw2MxN\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Plw2MxN',
    'container.build_id' => '24f92cde',
    'container.build_time' => 1542619009,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPlw2MxN');
